### ISSUE TITLE
`pytest` fails with python version `>= 12`

### ISSUE THREAD

**Issue by dominikgeissler** [LKlinke/Prodigy#40]
Running `pytest` with python version `3.12.3` produces the following error:

```console
> python -V
3.12.3
> pytest
    yield from importlib_metadata.entry_points().get("hypothesis", [])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'

```

Limiting `importlib-metadata` to `<5` as described [here](https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean) did not work. The same dependency versions work with python version `3.11.10`.
